# Copyright (c) 2022 Uber Technologies, Inc.
# 
# <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# <p>http://www.apache.org/licenses/LICENSE-2.0
# 
# <p>Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing permissions and
# limitations under the License.

# This file contains rules to the specific feature flag API.

#
# For @stale_flag_name = stale_flag and @treated = true
# Before 
#   TestEnum.stale_flag.isEnabled
# After 
#   true
#

[[rules]]
name = "replace_isToggleEnabled_with_boolean_literal"
query = """(
(navigation_expression
        target: (navigation_expression
            target: (simple_identifier)
            suffix: (navigation_suffix
                suffix: (simple_identifier) @param))
        suffix: (navigation_suffix
            suffix: (simple_identifier) @access_identifier)) @parameter_access
(#eq? @param "@stale_flag")
(#eq? @access_identifier "isEnabled")
)"""
replace_node = "parameter_access"
replace = "true"
holes = ["stale_flag"]

#
# Before 
#   true && abcd()
# After 
#   abcd()
#
[[rules]]
name = "true_and_something"
query = """(
(conjunction_expression
        lhs: (boolean_literal) @true
        rhs: (_) @rhs
    ) @conjunction_expression
(#eq? @true "true")
)"""
groups = ["Cleanup Rule"]
replace_node = "conjunction_expression"
replace = "@rhs"

#
# Before 
#   abcd() && true
# After 
#   abcd()
#
[[rules]]
name = "something_and_true"
query = """(
(conjunction_expression
        lhs: (_) @lhs
        rhs: (boolean_literal) @true
    ) @conjunction_expression
(#eq? @true "true")
)"""
groups = ["Cleanup Rule"]
replace_node = "conjunction_expression"
replace = "@lhs"

#
# Before 
#   !true
# After 
#   false
#
[[rules]]
name = "not_true"
query = """(
(prefix_expression
        operation: (bang)
        target: (boolean_literal) @true
        ) @not_expression
(#eq? @true "true")
)"""
replace_node = "not_expression"
replace = "false"

#
# Before 
#   !false
# After 
#   true
#
[[rules]]
name = "not_false"
query = """(
(prefix_expression
        operation: (bang)
        target: (boolean_literal) @false
    ) @not_expression
(#eq? @false "false")
)"""
replace_node = "not_expression"
replace = "true"

#
# Before 
#   true || abcd()
# After 
#   true
#
[[rules]]
name = "true_or_something"
query = """(
(disjunction_expression
        lhs: (boolean_literal) @true
        rhs: (_) 
    ) @disjunction_expression
(#eq? @true "true")
)"""
groups = ["Cleanup Rule"]
replace_node = "disjunction_expression"
replace = "true"


#
# Before 
#   abcd() || true
# After 
#   true
#
[[rules]]
name = "something_or_true"
query = """(
(disjunction_expression
        lhs: (_)
        rhs: (boolean_literal) @true 
    ) @disjunction_expression
(#eq? @true "true")
)"""
groups = ["Cleanup Rule"]
replace_node = "disjunction_expression"
replace = "true"

#
# Before 
#   false && abcd()
# After 
#   false
#
[[rules]]
name = "false_and_something"
query = """(
(conjunction_expression
        lhs: (boolean_literal) @false
        rhs: (_) 
    ) @conjunction_expression
(#eq? @false "false")
)"""
replace_node = "conjunction_expression"
replace = "false"

#
# Before 
#   abcd() && false
# After 
#   false
#
[[rules]]
name = "something_and_false"
query = """(
(conjunction_expression
        lhs: (_) @lhs
        rhs: (boolean_literal) @false
    ) @conjunction_expression
(#eq? @false "false")
)"""
replace_node = "conjunction_expression"
replace = "false"


# Before 
#   if placeholder() {
#     abcd()
#   } else if true {
#     efg()
#   } else {
#     hij()
#   }
# After 
#   if placeholder() {
#     abcd()
#   } else {
#     efg()
#   }
#
[[rules]]
name = "else_if_always_true"
query = """ (
(else)
(if_statement
        condition: (boolean_literal) @condition
        (statements) @if_block
        (_) 
    ) @if_else_block
(#eq? @condition "true")
)"""
replace_node = "if_else_block"
replace = "{ @if_block }"

# Before 
#   if true {
#     abcd()
#   } else {
#     hij()
#   }
# After 
#   abcd()
#
[[rules]]
name = "if_always_true"
query = """ (
(_) @previous_statement
(if_statement
        condition: (boolean_literal) @condition
        (statements) @if_block
        (_) 
    ) @if_else_block
(#eq? @condition "true")
(#not-eq? @previous_statement "else")
)"""
groups = ["Cleanup Rule"]
replace_node = "if_else_block"
replace = "@if_block"
