matrix:
  include:

    - language: java
      install: true
      os: linux
      dist: trusty
      jdk:
        - oraclejdk8
        - openjdk11
      before_script:
        - cd java/
      script:
        - ./gradlew verGJF build
      after_success:
        - ./gradlew jacocoTestReport coveralls
      cache:
        directories:
          - $HOME/.gradle

    - language: swift
      os: osx
      osx_image: xcode11.6
      env: SWIFT=5.2
      before_script:
        - cd swift/
      script:
        - sh package.sh 
        - sh test.sh

notifications:
  email: false
