name: JS Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  eslint:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ github.event_name == 'push' || needs.detect.outputs.js == 'true' }}
    env: 
        HUSKY_SKIP_INSTALL: 1
    steps:
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          # GITHUB_TOKEN in forked repositories is read-only
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: legacy/javascript
