name: Polyglot Piranha
on:
  pull_request:
  push: 
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build_and_test:
    name: Polyglot Piranha Build
    runs-on: ubuntu-latest
    needs: detect
    steps:
      - name: Checkout Piranha sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Run pre-commit 
        run : |
          python -m venv .env
          source .env/bin/activate
          pip install pre-commit
          cargo install taplo-cli --locked
          pre-commit run --all-files
      - name: Run unit and integration tests
        run: cargo build && cargo test -- --include-ignored
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Create virtualenv and install dependencies
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install maturin pytest
      - name: Run Python tests
        run: |
          source .env/bin/activate
          maturin develop
          pytest tests/tests.py
