name: Polyglot Piranha CI
on:
  pull_request:
  push: 
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
jobs:
  # runs change detection
  # this job allows build_and_test to have a single if
  changes:
    runs-on: ubuntu-latest
    outputs:
      polyglot: ${{ steps.filter.outputs.polyglot }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yaml'

  build_and_test:
    name: Polyglot Piranha Build
    runs-on: ubuntu-latest
    needs: changes
    # always running when it's a push
    # otherwise, only when modifications in polyglot's dir
    if: ${{ github.event_name == 'push' || needs.changes.outputs.polyglot == 'true' }}
    steps:
      - name: Checkout Piranha sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Build Piranha
        run: cargo build
        working-directory: polyglot/piranha
      - name: Clippy check
        run: cargo clippy
        working-directory: polyglot/piranha
      - run: cargo test
        working-directory: polyglot/piranha
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Create virtualenv and install dependencies
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install maturin pytest
        working-directory: polyglot/piranha
      - name: Run tests
        run: |
          source .env/bin/activate
          maturin develop
          pytest tests/tests.py
        working-directory: polyglot/piranha
