name: Polyglot Piranha
on:
  pull_request:
    branches:
      - master

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.polyglot == 'false' }}
    steps:
      - run: 'echo "No Polyglot changes; build is not required."'
